#!/usr/bin/env bash
# This script will display listening ports. That includes
# listening sockets too as well as the PID and name of the
# + program to which each socket belongs.

netstat -l --program
