#!/usr/bin/env bash
# This will contineously be writing "I am alive" to the
# file /tmp/my_process. Pauses two seconds in between 
# each message.

while true
do
  echo "I am alive!" >> /tmp/my_process
  sleep 2
done
