#!/usr/bin/env bash
# This script will re-configure an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.2 from 127.0.0.1
#   - facebook.com resolves to 8.8.8.8 from 31.13.66.35

cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
